### ISSUE TITLE
Full Integration w/Pay.gov (DUP)

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#341] opened 2018-12-13 12:51 UTC

**Comment by JessicaMarine** [comment] 2020-03-05 21:41
Per Tricia (Court's General Counsel): There is a provision that provides: “If the Agency obtains any information from an end-user and then intends to send that information to Pay.gov for processing, the Agency must include a link to Pay.gov's notices and agreements page when obtaining the information from the end-user.”

Not knowing exactly how the filing system works, I thought I’d bring it to your attention.  If we are collecting information from a petitioner that we will be sending on to pay.gov in connection with payment for example, we may need to add a pay.gov notice link on our page.  It may be that we just don’t do this, but rather just send them to pay.gov in the first place.

**Comment by JessicaMarine** [comment] 2020-03-05 21:43
Duplicate of #166

**Closed by JessicaMarine** 2020-03-05 21:43 UTC
Labels: Delay Ship Indefinitely - No
