### ISSUE TITLE
BUG: Mobile - Practitioner without cases updates address - NaN% in progress bar

### ISSUE THREAD

**Issue by rachaelparris** [flexion/ef-cms#7913] opened 2021-03-02 21:20 UTC
**Describe the Bug**
On mobile - Private practitioner without any cases updates address and is taken back to dashboard. NaN% displays in progress bar, and it does not disappear.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
migration

**Who were you logged in as?**
private practitioner with no cases (local: try `privatePractitioner3@example.com`)

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
quarterly testing

**To Reproduce**
1. Login as a private practitioner with no cases
2. Go to My Account
3. Update address
4. Progress bar displays

**Expected Behavior**
Progress bar should not display if practitioner has no cases

**Actual Behavior**
Progress bar displays with NaN%

**Screenshots**
![IMG_1301](https://user-images.githubusercontent.com/43251054/109716809-20a6af80-7b5a-11eb-8588-e360d4e02362.jpg)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by kkoskelin** [comment] 2021-05-12 16:34
I've only been able to replicate this error perhaps once in every 20-25 attempts.  It does not really appear to have anything to do with mobile mode, fwiw.  Some debug work is now on branch `7913-progress-nan`.
I'm stuck.  Leaving this for a time when others with socket experience can pitch in.

**Comment by matthopson** [comment] 2021-05-13 17:52
Some findings on this:

1) The generateChangeOfAddress is sending out a progress message at the start before going through cases. This is fine, except we don't verify that there are actually cases for the given privatePractitioner user. Which means we initially show the progress UI when we don't need to. Since we fetch all docket numbers associated with the privatePractioner, we can just conditionally send that progress message if the array is greater than 0. This is further exacerbated by a race condition (mentioned below).

2) Every time we open a socket, we check if there is one in existence and close it. Since this happens when the user is routed to the dashboard after the `user_contact_initial_update_complete` event is fired, there is a potential race condition where the socket could be closed and reopened when the subsequent `user_contact_full_update_complete` which shows the final Alert Success banner. Any events emitted by the server during this short window can cause the UI to be in an incomplete state. This condition is more likely to be present when updating the firm name on a privatePractitioner with no cases because everything happens quickly and those subsequent messages are more likely to be fired immediately after the UI starts the process of routing the app, creating a socket connection - but not before closing the old one - and there lies the problem. The socket is closed momentarily while those messages come through and the UI is borked.

**Comment by kkoskelin** [comment] 2021-05-13 19:25
While we are hoping that the occurrence of this bug is far more rare, we are not yet convinced that it is gone for good.

The real solution here is likely to be a more robust messaging solution in which messages get queued, and remain in the queue unless confirmed received by a socket recipient.

**Comment by JessicaMarine** [comment] 2021-05-20 19:38
When we deployed the bug fix for #7913 to the IRS test environment, it is now preventing all IRS attorneys from logging in. We definitely need to figure out what's happening and how to correct it before we can take that to `prod`.  Perhaps @Mike Marcotte (US Tax Court, DC, he/him) can explain the websocket issue the IRS has.

**Comment by mariahkannenberg** [comment] 2021-05-21 14:20
Blocked - waiting to hear back from IRS.

**Closed** 2021-06-02 18:56 UTC
Labels: Groomed, Low Severity, bug
