### ISSUE TITLE
Internal Users: Work Queue Read versus Unread Status

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#572] opened 2019-01-08 20:08 UTC
As an internal user, in order to easily know which work queue items I have viewed, I need them to have a read versus unread status.  

## Notes:
* This needs to be applied universally to all work queues.

**Comment by uxforgood** [comment] 2019-01-09 14:40
I believe this is a duplicate of #517

**Closed** 2019-01-09 14:42 UTC
